In [32]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
import pandas as pd

In [33]:
! pip install pandas


Defaulting to user installation because normal site-packages is not writeable


In [34]:
# preparing independent and dependent features
def prepare_data(timeseries_data, n_features):
	X, y =[],[]
	for i in range(len(timeseries_data)):
		# find the end of this pattern
		end_ix = i + n_features
		# check if we are beyond the sequence
		if end_ix > len(timeseries_data)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = timeseries_data[i:end_ix], timeseries_data[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return np.array(X), np.array(y)

In [35]:
timeseries_data_global= pd.read_csv("../Dataset/global_cases.csv")
timeseries_data_india= pd.read_csv("../Dataset/india_cases.csv")

In [36]:
timeseries_data_global.head()

Date  Cases
0  22/01/20    557
1  23/01/20    657
2  24/01/20    944
3  25/01/20   1437
4  26/01/20   2120

In [37]:
timeseries_data_india.head()

Date  Cases
0  22/01/20      0
1  23/01/20      0
2  24/01/20      0
3  25/01/20      0
4  26/01/20      0

In [38]:
global_cases=timeseries_data_global['Cases']


In [39]:
global_cases_array=np.array(global_cases)

In [40]:
global_cases_array

array([      557,       657,       944, ..., 676213378, 676392824,
       676570149])

In [41]:
india_cases=timeseries_data_india['Cases']

In [42]:
india_cases_array=np.array(india_cases)

In [43]:
india_cases_array

array([       0,        0,        0, ..., 44689919, 44690298, 44690738])

In [44]:
timestamps=10
X_prevdata_global,y_preddata_global=prepare_data(global_cases_array, timestamps)

In [45]:
print(X_prevdata_global)

[[      557       657       944 ...      6169      8237      9927]
 [      657       944      1437 ...      8237      9927     12038]
 [      944      1437      2120 ...      9927     12038     16787]
 ...
 [674978793 675044414 675171439 ... 675968775 676024901 676082941]
 [675044414 675171439 675322238 ... 676024901 676082941 676213378]
 [675171439 675322238 675542852 ... 676082941 676213378 676392824]]


In [46]:
print(y_preddata_global)

[    12038     16787     19887 ... 676213378 676392824 676570149]


In [47]:
n_feature=1
X_prevdata_global=X_prevdata_global.reshape((X_prevdata_global.shape[1],X_prevdata_global.shape[2],n_feature))

IndexError: tuple index out of range

In [48]:
X_prevdata_global=np.array(X_prevdata_global)

In [49]:
X_prevdata_global.shape

(1133, 10)

In [50]:
model = Sequential()
model.add(LSTM(65, activation='relu', return_sequences=True, input_shape=(timestamps, n_feature)))
model.add(LSTM(65, activation='relu'))
model.add(LSTM(65, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X_prevdata_global,y_preddata_global, epochs=100, verbose=1)

/Users/swoyamsiddharth/Library/Python/3.9/lib/python/site-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


ValueError: Input 0 of layer "lstm_5" is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (None, 65)